'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Consulta_Chamado

    '''<summary>
    '''hfNewUserNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNewUserNumber As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfNewAreaCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNewAreaCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfTelecomProvider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTelecomProvider As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfUserNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfUserNumber As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfIdAtivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdAtivo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfIdConsumidor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdConsumidor As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfNewPlanoContrato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNewPlanoContrato As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfIdConglomerado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdConglomerado As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfIdChamado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdChamado As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfEmailEnviado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfEmailEnviado As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfTipoSolicitacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTipoSolicitacao As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfComentarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfComentarios As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfEstado As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfRequestNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRequestNumber As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfWorkOrderNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfWorkOrderNumber As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfUserName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfNrAtivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNrAtivo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfEmailsSelecionados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfEmailsSelecionados As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfEmailResponsavelRegional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfEmailResponsavelRegional As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfServicePack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfServicePack As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfNovaLinha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNovaLinha As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfMigrationDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfMigrationDevice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfnomePlanoMigracaoNL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfnomePlanoMigracaoNL As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfOriginalMigrationDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOriginalMigrationDevice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfNomePlanoPortabilidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNomePlanoPortabilidade As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfDataEfetivacaoPortabilidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDataEfetivacaoPortabilidade As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfDataRecebimentoChip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDataRecebimentoChip As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfAlterarLinha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAlterarLinha As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfFaturaDropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFaturaDropdown As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfDesignationProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDesignationProduct As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfNovoSimCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNovoSimCard As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfCancellationComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCancellationComment As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfNovoPlanoMigracao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNovoPlanoMigracao As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''hfOriginalFlManual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOriginalFlManual As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtBusca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBusca As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnBusca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBusca As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLimparBusca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimparBusca As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rptChamados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptChamados As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btnPreviousPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPreviousPage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblPageNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnNextPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextPage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddlItemsPerPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlItemsPerPage As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbBotao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBotao As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btVoltar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btVoltar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''modalTipoSolicitacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalTipoSolicitacao As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''modalIdChamadoContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalIdChamadoContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''modalIdChamado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalIdChamado As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''camposCondicionaisContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents camposCondicionaisContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnExecutar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExecutar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtMotivoCancelamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotivoCancelamento As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''btnConfirmarCancelamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmarCancelamento As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rightColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rightColumn As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''empresaContratante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents empresaContratante As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''faturaDropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents faturaDropdown As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''corpoEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents corpoEmail As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''selectedEmails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedEmails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hfBase64Files control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfBase64Files As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''emailResponsavelRegional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailResponsavelRegional As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnEnviarEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnviarEmail As Global.System.Web.UI.WebControls.Button
End Class
