'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Consumidor

    '''<summary>
    '''pnlConfirmacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlConfirmacao As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMenssagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMenssagem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btContinuar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btContinuar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btRestaurar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btRestaurar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''HiddenField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlObservacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlObservacao As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDLinhaConta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDLinhaConta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtObservacaoObrigatoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacaoObrigatoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvObservacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvObservacao As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btCancela control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCancela As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btOk As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfdId_Aparelho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfdId_Aparelho As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRegistro As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDescRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescRegistro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblObservacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObservacao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtObservacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFinalidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalidade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFinalidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFinalidade As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtIndentificacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIndentificacao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btFechar_Registro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btFechar_Registro As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblDescricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescricao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDescricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescricao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvDescricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDescricao As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMatricula As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMatricula As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMatricula As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEMail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvEMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvEMail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblEmailCopia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmailCopia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEmailCopia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailCopia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPoliticaUso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPoliticaUso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtValorPolitica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorPolitica As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''mevValorPolitica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mevValorPolitica As Global.AjaxControlToolkit.MaskedEditValidator

    '''<summary>
    '''lblMatricula_Chefia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMatricula_Chefia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMatricula_Chefia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMatricula_Chefia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblConsumidorTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConsumidorTipo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboConsumidorTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboConsumidorTipo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvConsumidorTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvConsumidorTipo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblEmpresaContratada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpresaContratada As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboEmpresaContratada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEmpresaContratada As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCargo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCargo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblFilial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFilial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboFilial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFilial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvFilial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvFilial As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblCentroCusto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCentroCusto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCentroCusto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCentroCusto As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvCentroCusto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCentroCusto As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblDepartamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDepartamento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboDepartamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDepartamento As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSetor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSetor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboSetor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSetor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSecao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSecao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboSecao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSecao As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboConsumidorStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboConsumidorStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkFl_Nao_Enviar_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFl_Nao_Enviar_Email As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DivAtivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivAtivo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgAtivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgAtivo As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''lblUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsuario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtIdUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdUsuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNmUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNmUsuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblIdentificacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdentificacao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtIdentificacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdentificacao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlValidador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlValidador As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''vceDescricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vceDescricao As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''vceMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vceMatricula As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''vceEMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vceEMail As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''vceFilial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vceFilial As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''vceConsumidorTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vceConsumidorTipo As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''vceCentroCusto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vceCentroCusto As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''meeValorPolitica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents meeValorPolitica As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbBotao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBotao As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btVoltar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btVoltar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btLimpar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSalvar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btDesativar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btDesativar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblEncerrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEncerrar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btConfiguracao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btConfiguracao As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Span2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Span2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btAbrir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btAbrir As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As IControlIT.Principal
        Get
            Return CType(MyBase.Master, IControlIT.Principal)
        End Get
    End Property
End Class
